### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by RyanSquared** [ChickenNuggers/Moon-Moon#1]
### Moon Moon
- [X] ~~Logging of data~~
  - [X] ~~Log rotation~~
- [x] Finish data module
- [ ] Configuration ~~editor~~ generator
- [x] Write output module
- [X] Commands module
- [x] CAP module (transferring capabilities to server)
- [x] Add in on-connect handlers
- [x] Tags support
  - [x] Move over patched version from lua-irc-engine
- [ ] IRCv3 Capabilities
  - [ ] IRCv3.1
    - [x] `multi-prefix`
    - [ ] `sasl`
    - [x] `account-notify`
    - [x] `away-notify`
    - [x]  `extended-join`
    - [ ] `tls`
  - [ ] IRCv3.2
    - [ ] `metadata`
    - [ ] `monitor`
    - [x] `account-tag`
    - [ ] `batch`
    - [x] `cap-notify`
    - [x] `chghost`
    - [x] `echo-message`
    - [x] `invite-notify`
    - [ ] `sasl`
    - [x] `server-time`
    - [x] `userhost-in-names`
- [x] Nick messages and data
